---

driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: false
  instance_type: t2.micro
  associate_public_ip: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: default
